type = "branch"

label = "Branch 4"

[position]
x = -100
y = 350

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
quantity = 1
type = "Source"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

