type = "branch"

label = "Branch 7"

[position]
x = 250
y = 380

[[block]]
quantity = 1
type = "Source"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Sink"
