type = "branch"
label = "Branch 6"

[position]
x = 890.4092464146261
y = 119.54879005548366

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
