type = "branch"
label = "Branch 7"

[position]
x = 47.67411300919845
y = 484.08672798948754

[[block]]
type = "Source"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
