type = "branch"
label = "Branch 7"

[position]
x = 251.67411300919844
y = 708.0867279894876

[[block]]
type = "Source"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
