type = "branch"
label = "Branch 8"

location = "onshore"

[position]
x = -54.64153667556634
y = 187.40376949866504

[[outgoing]]
target = "branch-5"
weight = 1

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Ship"
