type = "branch"
label = "Branch 3"

[position]
x = 537.2544803986066
y = -346.1051657989993

[[block]]
type = "Port"

[[block]]
type = "Pipe"
diameter = "0.75 m"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
