type = "branch"
label = "Branch 1 example"
parentId = "group-1"

location = "onshore"

[position]
x = 20
y = 30

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = "100 bar"

[[block]]
quantity = 4
type = "Capture Unit"

[[block]]
type = "Pipe"
length = "1000 m"

[[block]]
type = "Compressor"

[[block]]
type = "Cooler"
