type = "branch"
label = "Branch 5"

[position]
x = 800
y = 350

[[outgoing]]
target = "branch-6"
weight = 1

[[block]]
type = "Port"

[[block]]
type = "Pipe"
diameter = "0.75 m"

[[block]]
type = "Ship"
