type = "branch"
label = "Branch 4"

[position]
x = -726.1051248357425
y = 29.169513797634693

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = "15.5 bar"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
