type = "branch"
label = "Branch 4"

[position]
x = -280.10512483574246
y = 351.1695137976347

[[outgoing]]
target = "branch-2"
weight = 1

[[block]]
type = "Source"
pressure = "15.5 bar"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"
