type = "branch"
label = "Branch 3"

[position]
x = 900
y = 150

[[block]]
type = "Port"

[[block]]
type = "Pipe"
diameter = "0.75 m"

[[block]]
type = "Pipe"

[[block]]
type = "Pipe"

[[block]]
type = "Sink"
